"run_name": "HardBn_NoDemoDecay"
"project": "Robomaze-TrainingNavigator"  # "Robomaze-tests"
"config_file": "BN_NoKillOnWall.yaml"
"show_gui": False
"seed": !!python/object/apply:eval
  [41**3]
"train_steps": !!python/object/apply:eval
  [5 * 10 ** 6]

# Training and environment parameters
"num_envs": 3
"learning_rate": 0.5e-5
"grad_clip_norm_actor": 30
"grad_clip_norm_critic": 1
"batch_size": 2048
"buffer_size": !!python/object/apply:eval
  [1 * 10 ** 5]
"actor_arch": !!python/tuple [400, 300]  # Should not be changed or explored
"critic_arch": !!python/tuple [400, 300]  # Should not be changed or explored
"exploration_noise_std": 0.03
"epsilon_to_subgoal": 0.5  # DO NOT TOUCH
"max_velocity_in_subgoal": 3  # DO NOT TOUCH
"stepper_radius_range": !!python/tuple [0.6, 2.5]  # DO NOT TOUCH
"done_on_collision": False  # modify rewards in case you change this
"rewards":
  !Rewards
    target_arrival: 1
    collision: -0.02
    fall: -1
    idle: -0.001
"demo_on_fail_prob": 0.5
"demo_prob_decay": 0.999
"use_demo_epsilon_offset": True
"learning_starts": !!python/object/apply:eval
  [10 ** 4]

"velocity_in_obs": False
"max_stepper_steps": 100
"max_navigator_steps": 30

# workspace paths:
"maze_map_path": "TrainingNavigator/maps/bottleneck.png"
"workspaces_path": 'TrainingNavigator/workspaces/bottleneckXL.npy'
"demonstration_path": 'TrainingNavigator/workspaces/bottleneckXL_short1.5_trajectories.npz'
"stepper_agent_path": 'TrainingNavigator/StepperAgents/StepperV2_F2000_MoreNoise.pt'

# logging parameters
"eval_workspaces": 100  # will take the first workspaces
"eval_freq": 10000
"video_freq": 1
"save_model_freq": 10000

# Constants:
"maze_size": !!python/tuple [10, 10]
