"run_name": "Unnamed"
"group": ""
"show_gui": False
"seed": !!python/object/apply:eval
  [43 ** 3]

"robot_type": "Ant"
"num_envs": 1
"train_steps": 25000000
"buffer_size": 500000
"learning_starts": 10000
"timeout_steps": 150
"map_radius": 5
"learning_rate": 0.5e-5
"gamma": 0.99
"tau": 0.005
"reduce_lr": True
"lr_reduce_factor": 0.2
"exploration_noise_std": 0.1
"batch_size": 512
"rewards":
  !Rewards
    target_distance_weight: 0.01
    target_distance_offset: 5  # reward will be weight*(offset - distance)
    rotation_weight: 0.00
    fall: -1
    target_arrival: 1
    collision: 0
    timeout: 0
    idle: 0
    height_weight: 0.0
done_on_goal_reached: False
success_steps_before_done: 1 # The minimum number of steps the robot must be at the target to end episode,
                            # ignored when done_on_goal_reached is False

sticky_actions: 8

"use_td3": False  # otherwise DDPG
# td3 specific parameters, ignored if use_td3=False
"td3_smoothing_noise": 0.2
"td3_smoothing_noise_clip": 0.5
"td3_policy_delay": 2
"td3_n_critics": 2

"max_goal_velocity": 9999
"target_epsilon": 0.25
"target_heading_epsilon": 3.15 # removes the requirement of the target heading
"random_initialization": True
"with_obstacles": False

"eval_freq": !!python/object/apply:eval [2 * 10 ** 5]
"video_freq": 1
